import { mkdir } from "node:fs/promises";
import { runMedia, ffmpegBase } from "../src/main/media/process.ts";

await mkdir("work", { recursive: true });
await runMedia("ffmpeg", [
   ...ffmpegBase,
   "-f",
   "lavfi",
   "-i",
   "testsrc2=size=960x540:rate=30:duration=18",
   "-f",
   "lavfi",
   "-i",
   "sine=frequency=440:sample_rate=48000:duration=18",
   "-f",
   "lavfi",
   "-i",
   "sine=frequency=880:sample_rate=48000:duration=18",
   "-map",
   "0:v",
   "-map",
   "1:a",
   "-map",
   "2:a",
   "-c:v",
   "libx264",
   "-preset",
   "fast",
   "-crf",
   "20",
   "-g",
   "60",
   "-keyint_min",
   "60",
   "-sc_threshold",
   "0",
   "-pix_fmt",
   "yuv420p",
   "-c:a",
   "aac",
   "-movflags",
   "+faststart",
   "work/fixture.mp4",
]);
await runMedia("ffmpeg", [...ffmpegBase, "-i", "work/fixture.mp4", "-map", "0", "-c", "copy", "work/fixture.mkv"]);
await runMedia("ffmpeg", [
   ...ffmpegBase,
   "-i",
   "work/fixture.mp4",
   "-map",
   "0",
   "-c:v",
   "libx265",
   "-preset",
   "fast",
   "-x265-params",
   "keyint=60:min-keyint=60:scenecut=0:open-gop=0:log-level=error:pools=4",
   "-crf",
   "20",
   "-c:a",
   "copy",
   "work/fixture-hevc.mp4",
]);
await runMedia("ffmpeg", [
   ...ffmpegBase,
   "-i",
   "work/fixture.mp4",
   "-map",
   "0",
   "-c",
   "copy",
   "-metadata:s:a:0",
   "handler_name=Game audio",
   "-metadata:s:a:1",
   "handler_name=Microphone",
   "work/named-audio.mp4",
]);
console.log("Created 18-second H.264/MP4, H.264/MKV, HEVC/MP4 and named-audio fixtures with two audio tracks.");
