import { expect } from "@playwright/test";
import { test, waitForVideo } from "./app.mjs";
import { resolve } from "node:path";

test("export dialog", async ({ launchApp, profile }) => {
   const app = await launchApp(profile, resolve("work/fixture.mp4"));
   const page = await app.firstWindow();
   await waitForVideo(page);
   const bar = await page.locator(".timeline-viewport").boundingBox();
   await page.mouse.click(bar.x + bar.width / 3, bar.y + 36);
   await page.keyboard.press("s");
   await expect(page.getByRole("slider", { name: "Clip 2 start", exact: true })).toBeVisible();
   await page.mouse.click(bar.x + bar.width * 0.8, bar.y + 36);
   await expect(page.locator("[data-command=merge]")).toBeDisabled();
   await expect(page.locator("[data-command=split]")).toBeEnabled();
   const handle = page.getByRole("slider", { name: "Clip 1 end", exact: true });
   const target = Number(await handle.getAttribute("aria-valuenow"));
   await handle.click();
   await expect.poll(() => page.locator("video").evaluate((v) => v.currentTime)).toBeCloseTo(target, 2);
   console.log("Handle click seeks correctly:", target);
   // The forgiving seam target belongs to Merge, even when slightly off the cut.
   await page.mouse.click(bar.x + (bar.width * target) / 18 + 6, bar.y + 36);
   await expect(page.locator("[data-command=merge]")).toBeEnabled();
   await expect(page.locator("[data-command=split]")).toBeDisabled();
   await page.locator("[data-command=merge]").click();
   await expect(page.locator(".clip-range:not(.exiting)")).toHaveCount(1);
   await expect.poll(() => page.locator("video").evaluate((v) => v.currentTime)).toBeCloseTo(target, 2);
   await expect(page.locator("[data-command=split]")).toBeEnabled();
   await page.keyboard.press("s");
   await expect(page.getByRole("slider", { name: "Clip 2 start", exact: true })).toHaveAttribute("aria-valuenow", String(target));
   await page.getByRole("button", { name: "Export", exact: true }).click();
   await page.getByRole("button", { name: "Merged Video", exact: true }).click();
   await page.getByLabel("Combined filename", { exact: true }).fill("retained");
   await page.getByLabel("Save to", { exact: true }).fill(profile + "/new-folder");
   await page.getByRole("button", { name: "Audio tracks to export", exact: true }).click();
   await page.getByRole("option").last().click();
   await expect(page.getByRole("button", { name: "Audio tracks to export", exact: true })).not.toContainText("All audio tracks");
   await page.getByRole("button", { name: "Close panel", exact: true }).last().click();
   await expect(page.getByRole("dialog")).toHaveCount(0);
   await page.getByRole("button", { name: "Export", exact: true }).click();
   await expect(page.getByLabel("Combined filename", { exact: true })).toHaveValue("retained");
   await expect(page.getByRole("button", { name: "Audio tracks to export", exact: true })).not.toContainText("All audio tracks");
   await page.getByRole("button", { name: "Export video", exact: true }).click();
   await expect(page.getByRole("dialog", { name: "Create output folder?", exact: true })).toBeVisible();
   await page.waitForTimeout(200);
   await page.getByRole("button", { name: "Cancel", exact: true }).click();
   await expect(page.getByRole("dialog", { name: "Export video", exact: true })).toBeVisible();
   await page.getByRole("button", { name: "Export video", exact: true }).click();
   await page.getByRole("button", { name: "Create folder and export", exact: true }).click();
   await expect(page.getByRole("button", { name: "Open file", exact: true })).toBeVisible({ timeout: 60000 });
   await page.getByRole("button", { name: "Export", exact: true }).click();
   await page.getByRole("button", { name: "Export video", exact: true }).click();
   await expect(page.getByRole("dialog", { name: "Replace existing file?", exact: true })).toBeVisible();
   await page.waitForTimeout(200);
   await page.getByRole("button", { name: "Replace and export", exact: true }).click();
   await expect(page.getByRole("dialog")).toHaveCount(0);
   await expect(page.getByRole("button", { name: "Open file", exact: true })).toBeVisible({ timeout: 60000 });
   await page.getByRole("button", { name: "Export", exact: true }).click();
   await page.getByRole("button", { name: "Separate clips", exact: true }).click();
   await page.getByRole("textbox", { name: "Clip 1 filename", exact: true }).fill("first-kept-name");
   await page.getByRole("checkbox", { name: "Export clip 2", exact: true }).uncheck();
   await page.keyboard.press("Escape");
   await expect(page.getByRole("dialog")).toHaveCount(0);
   await page.getByRole("button", { name: "Export", exact: true }).click();
   await expect(page.getByRole("button", { name: "Separate clips", exact: true })).toHaveAttribute("aria-pressed", "true");
   await expect(page.getByRole("textbox", { name: "Clip 1 filename", exact: true })).toHaveValue("first-kept-name");
   await expect(page.getByRole("checkbox", { name: "Export clip 2", exact: true })).not.toBeChecked();
   console.log("Export persistence, missing folder, cancel and overwrite passed");
});
