import { expect } from "@playwright/test";
import { test } from "./app.mjs";
import { resolve, join } from "node:path";
import { mkdir, readdir } from "node:fs/promises";

test("export workflow", async ({ launchApp, profile }) => {
   const output = join(profile, "exports");
   await mkdir(output);
   const app = await launchApp(profile, resolve("work/fixture.mp4"));
   const page = await app.firstWindow();
   const waitForTime = (time) => page.waitForFunction((target) => Math.abs(document.querySelector("video").currentTime - target) < 0.05, time);
   await page.waitForFunction(() => document.querySelector("video")?.readyState >= 2);
   await page.getByRole("button", { name: "Fullscreen video", exact: true }).click();
   await page.waitForFunction(() => document.fullscreenElement?.tagName === "VIDEO");
   await page.evaluate(() => document.exitFullscreen());
   await page.waitForFunction(() => !document.fullscreenElement);
   const scrub = await page.evaluate(async () => {
      const sourceId = decodeURIComponent(new globalThis.URL(document.querySelector("video").currentSrc).pathname.replace(/^\//, ""));
      const data = await globalThis.desktop.scrubAudio(sourceId, [1]);
      return { sampleRate: data?.sampleRate, bytes: data?.pcm?.byteLength ?? 0 };
   });
   expect(scrub.sampleRate).toBe(22050);
   expect(scrub.bytes).toBeGreaterThan(22050 * 2);
   const bar = await page.locator(".timeline-viewport").boundingBox();
   await page.mouse.move(bar.x + bar.width * 0.1, bar.y + 36);
   await page.mouse.down();
   await page.mouse.move(bar.x + bar.width * 0.4, bar.y + 36, { steps: 12 });
   await page.waitForFunction(() => Math.abs(document.querySelector("video").currentTime - 7.2) < 0.05);
   await page.mouse.up();
   await page.keyboard.press("s");
   const start = page.getByRole("textbox", { name: "Clip start", exact: true });
   const end = page.getByRole("textbox", { name: "Clip end", exact: true });
   await start.fill("00:09.00");
   await start.press("Tab");
   await end.fill("00:16.00");
   await end.press("Tab");
   await page.locator("video").evaluate((v) => {
      v.currentTime = 12;
   });
   await waitForTime(12);
   await page.getByRole("button", { name: "Previous clip", exact: true }).click();
   await waitForTime(9);
   await page.getByRole("button", { name: "Previous clip", exact: true }).click();
   await page.waitForFunction(() => Math.abs(document.querySelector("video").currentTime - 7.2) < 0.05);
   await page.getByRole("button", { name: "Next clip", exact: true }).click();
   await waitForTime(9);
   const originalUrl = await page.locator("video").getAttribute("src");
   await page.getByRole("button", { name: "Preview audio tracks", exact: true }).click();
   await page.getByRole("option").nth(1).click();
   await page.getByRole("option").nth(0).click();
   await expect(page.getByText(/preparing a playable preview|compatible preview/i)).toHaveCount(0);
   await expect(page.locator("video")).not.toHaveAttribute("src", originalUrl);
   await page.getByRole("button", { name: "Snap to keyframes", exact: true }).click();
   await expect(page.getByRole("button", { name: "Snap to keyframes", exact: true })).toHaveAttribute("aria-pressed", "true");
   expect(await page.locator(".keyframe-tick").count()).toBeGreaterThan(0);
   const handle = page.getByRole("slider", { name: "Clip 2 start", exact: true });
   const rect = await handle.boundingBox();
   await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
   await page.mouse.down();
   await page.mouse.move(bar.x + (bar.width * 10.8) / 18, bar.y + 36, { steps: 8 });
   await page.mouse.up();
   await expect(handle).toHaveAttribute("aria-valuenow", "10");
   await page.getByRole("button", { name: "Export current frame", exact: true }).click();
   await page.getByRole("dialog", { name: "Export current frame", exact: true }).waitFor();
   expect(await page.getByRole("button", { name: "Close panel" }).evaluate((button) => button === document.activeElement)).toBe(false);
   await page.getByRole("textbox", { name: "Save frame to", exact: true }).fill(output);
   await page.getByRole("textbox", { name: "Frame filename", exact: true }).fill("test-frame");
   await page.getByRole("button", { name: "Export frame", exact: true }).click();
   await page.getByRole("status").filter({ hasText: "Frame exported" }).waitFor();
   expect(await readdir(output)).toContain("test-frame.png");
   await page.keyboard.press("Escape");
   await page.getByRole("button", { name: "Export", exact: true }).click();
   await page.getByRole("button", { name: "Merged Video", exact: true }).click();
   await page.getByLabel("Save to", { exact: true }).fill(output);
   await page.getByRole("textbox", { name: "Combined filename", exact: true }).fill("joined");
   await expect(page.getByRole("button", { name: "Audio tracks to export", exact: true })).toContainText("All audio tracks");
   await expect(page.getByRole("button", { name: "Export video", exact: true })).toBeEnabled();
   await expect(page.getByText("Cut details", { exact: true })).toHaveCount(0);
   await page.getByRole("button", { name: "Export video", exact: true }).click();
   await page.getByText("Export complete", { exact: true }).waitFor({ timeout: 60000 });
   expect(await readdir(output)).toContain("joined.mp4");
   await page.getByRole("button", { name: "Dismiss export status", exact: true }).click();
   await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(800, 560));
   const controls = await page.locator(".transport").boundingBox();
   expect(controls.y + controls.height).toBeLessThanOrEqual(560);
   const volume = await page.getByRole("button", { name: "Playback settings", exact: true }).boundingBox();
   expect(volume.x + volume.width).toBeLessThanOrEqual(800);
   console.log("PASS compact UI, scrubbing, boundary navigation, multi-track audio, snapping, frame export, merged export, and 800x560 layout");
});
