import { expect } from "@playwright/test";
import { test, waitForVideo } from "./app.mjs";
import { resolve } from "node:path";

test("shortcuts", async ({ launchApp, profile }) => {
   const app = await launchApp(profile, resolve("work/fixture.mp4"));
   const page = await app.firstWindow();
   await waitForVideo(page);
   const seek = async (time) => {
      const bar = await page.locator(".timeline-viewport").boundingBox();
      await page.mouse.click(bar.x + (bar.width * time) / 18, bar.y + 36);
      await page.waitForTimeout(150);
   };
   await seek(6);
   await page.keyboard.press("s");
   await expect(page.locator(".clip-range")).toHaveCount(2);
   await expect(page.locator("[data-command=merge]")).toBeEnabled();
   await page.keyboard.press("e");
   await expect(page.locator(".clip-range")).toHaveCount(1);
   await page.keyboard.press("ControlOrMeta+z");
   await expect(page.locator(".clip-range")).toHaveCount(2);
   await seek(8);
   await page.keyboard.press("w");
   await expect(page.locator(".clip-range")).toHaveCount(1);
   await page.keyboard.press("w");
   await expect(page.locator(".clip-range")).toHaveCount(2);
   await page.keyboard.press("m");
   await expect(page.locator("video")).toHaveJSProperty("muted", true);
   await page.keyboard.press("m");
   await expect(page.locator("video")).toHaveJSProperty("muted", false);
   await page.keyboard.press("c");
   await expect(page.locator("[data-command=snap]")).toHaveAttribute("aria-pressed", "true");
   await page.keyboard.press("c");
   await seek(9);
   await page.keyboard.press("a");
   await expect(page.getByRole("slider", { name: "Clip 2 start", exact: true })).toHaveAttribute("aria-valuenow", /9/);
   await seek(12);
   await page.keyboard.press("d");
   await expect(page.getByRole("slider", { name: "Clip 2 end", exact: true })).toHaveAttribute("aria-valuenow", /12/);
   await seek(10);
   await page.keyboard.press(".");
   await page.waitForTimeout(200);
   const after = await page.locator("video").evaluate((video) => video.currentTime);
   expect(after).toBeGreaterThan(10);
   expect(after).toBeLessThan(10.1);
   await page.keyboard.press(",");
   await page.waitForTimeout(100);
   expect(await page.locator("video").evaluate((video) => video.currentTime)).toBeCloseTo(10, 3);
   console.log("Shortcut and merge workflow passed");
});
